<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wtJTrDy' shared service.

return $this->privates['.service_locator.wtJTrDy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdController::index' => ['privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true],
    'App\\Controller\\AdController::show' => ['privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true],
    'App\\Controller\\AdController:index' => ['privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true],
    'App\\Controller\\AdController:show' => ['privates', '.service_locator.m2hZxMx', 'get_ServiceLocator_M2hZxMxService.php', true],
], [
    'App\\Controller\\AdController::index' => '?',
    'App\\Controller\\AdController::show' => '?',
    'App\\Controller\\AdController:index' => '?',
    'App\\Controller\\AdController:show' => '?',
]);
