<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU7Dophb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7Dophb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU7Dophb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU7Dophb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU7Dophb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U7Dophb',
    'container.build_id' => '5c2ae5e8',
    'container.build_time' => 1566035852,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU7Dophb');
