<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtB4wxW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtB4wxW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWtB4wxW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWtB4wxW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWtB4wxW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WtB4wxW',
    'container.build_id' => 'f8af0250',
    'container.build_time' => 1565526769,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtB4wxW');
