<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxAFDgY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxAFDgY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxAFDgY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxAFDgY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIxAFDgY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IxAFDgY',
    'container.build_id' => '8c164caf',
    'container.build_time' => 1566034656,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxAFDgY');
